version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: onliner_password
      POSTGRES_USER: onliner_user
      POSTGRES_DB: onliner_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
      