# Generated by Django 3.1.7 on 2021-04-13 15:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(default='Empty'),
            preserve_default=False,
        ),
    ]
