# Generated by Django 3.1.7 on 2021-04-14 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210413_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news'),
        ),
        migrations.DeleteModel(
            name='EditingHistoryEntry',
        ),
    ]
