# Generated by Django 3.1.7 on 2021-03-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterUniqueTogether(
            name='cart_product_m2m',
            unique_together={('cart', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='order_product_m2m',
            unique_together={('order', 'product')},
        ),
    ]
