# Generated by Django 3.1.7 on 2021-03-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210321_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproductm2m',
            options={'verbose_name': 'product'},
        ),
        migrations.AlterModelOptions(
            name='orderproductm2m',
            options={'verbose_name': 'product'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('paid', 'Paid'), ('closed', 'Closed')], default='incomplete', max_length=16),
        ),
    ]
