name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          checkName: "Python Lint"
          exclude: "*migrations*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
